# Arrays and ufuncs(Universal functions) operations you can perform on arrays

In numpy we work with arrays in any dimention 
Ufuncs are built in functions that let us do math with those arrays(square every element of this array, add two arrays together,multiply two arrays together etc..Think back to matrix multiplication)


We can create these ones but generally these are built in ones  

In [5]:
import numpy as np

In [8]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
res=np.multiply(arr1,arr2)
print(res)

[ 4 10 18]


# Arrays can be manually resized by us needed - with things like flatten().


In [20]:
#Taking a multi dimentional array and flattening it into a single dimentional array 
#.ravel() 
arr_toflatten=np.random.rand(1,2,3,4)
display(arr_toflatten)
flattend_array=arr_toflatten.flatten()
display(flattend_array)

array([[[[0.23091307, 0.9094358 , 0.93722426, 0.49456188],
         [0.68943108, 0.77733475, 0.58387479, 0.38411293],
         [0.34621094, 0.91087178, 0.18904976, 0.54525095]],

        [[0.89590306, 0.5540657 , 0.91132877, 0.13929027],
         [0.90370187, 0.93799209, 0.13046044, 0.05040845],
         [0.86489813, 0.58932237, 0.07597465, 0.40641224]]]])

array([0.23091307, 0.9094358 , 0.93722426, 0.49456188, 0.68943108,
       0.77733475, 0.58387479, 0.38411293, 0.34621094, 0.91087178,
       0.18904976, 0.54525095, 0.89590306, 0.5540657 , 0.91132877,
       0.13929027, 0.90370187, 0.93799209, 0.13046044, 0.05040845,
       0.86489813, 0.58932237, 0.07597465, 0.40641224])

In [25]:
# Lets try with the squezzing of different diamentional arrays
m=np.random.rand(1,2,3,4)
n = np.squeeze(arr_toflatten)
display(n)


array([[[0.23091307, 0.9094358 , 0.93722426, 0.49456188],
        [0.68943108, 0.77733475, 0.58387479, 0.38411293],
        [0.34621094, 0.91087178, 0.18904976, 0.54525095]],

       [[0.89590306, 0.5540657 , 0.91132877, 0.13929027],
        [0.90370187, 0.93799209, 0.13046044, 0.05040845],
        [0.86489813, 0.58932237, 0.07597465, 0.40641224]]])